# Generated by Django 3.0.3 on 2020-02-21 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_userdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='month',
            field=models.CharField(default='Some String', max_length=15),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.IntegerField(),
        ),
    ]
