# Generated by Django 3.0.3 on 2020-02-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20200221_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseFeb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField()),
                ('expense', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseJan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField()),
                ('expense', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
